baseURL = "https://seblavoie.com/"
theme = "ananke"
googleAnalytics = "UA-11152642-4"

DefaultContentLanguage = "en"

languageName = "English"
languageCode = "en-us"
locale = "en"

enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  facebook = ""
  twitter = "https://twitter.com/sebastienlavoie"
  instagram = ""
  youtube = ""
  github = "https://github.com/seblavoie"
  linkedin = "https://www.linkedin.com/in/seblavoie/"
  recent_posts_number = 2



[languages]
  [languages.en]
    title = "Sebastien Lavoie - Freelance motion designer"
    description = "Freelance motion designer and After Effects script developer from Québec, Canada"
    footerCta = "Got a project in mind? Let’s talk!"
    weight = 1
    [[languages.en.menu.main]]
        url    = "/portfolio"
        name   = "Portfolio"
        weight = 1

    [[languages.en.menu.main]]
        url    = "/blog"
        name   = "Blog"
        weight = 2

    [[languages.en.menu.main]]
        url    = "/about-me"
        name   = "About me"
        weight = 3

    [[languages.en.menu.main]]
        url    = "/fr"
        name   = "Français"
        weight = 4

  [languages.fr]
    title = "Sebastien Lavoie - Motion designer pigiste"
    description = "Freelance motion designer and After Effects script developer from Québec, Canada"
    weight = 2
    footerCta = "Un projet en tête? Écris-moi!"
    locale = "fr"
    languageCode = "fr-ca"
    languageName = "Français"

    [[languages.fr.menu.main]]
        url    = "/fr/portfolio"
        name   = "Portfolio"
        weight = 1

    [[languages.fr.menu.main]]
        url    = "/blog"
        name   = "Blogue (anglais)"
        weight = 2

    [[languages.fr.menu.main]]
        url    = "/fr/about-me"
        name   = "À propos"
        weight = 3

    [[languages.fr.menu.main]]
        url    = "/"
        name   = "Anglais"
        weight = 4

[taxonomies]
  tag = "tags"
  category = "categories"
